### ISSUE TITLE
Support for HC05

### ISSUE THREAD

**Issue by Jerther** [houkanshan/arduino-bt-hid-proxy#1]
Hi!

From your experience, what would it take to replace the USB BT Dongle and the USB shield by one of those HC05 modules? I'd like to make one, and eventually contribute to your project but first I'd like some hint what I'd be getting into ;)

**Comment by houkanshan** [comment]
Hi Jerther, to use the HC05 module you will need to turn it into a Bluetooth HID Host, just like what the USB BT Dongle + USB shield do. Unfortunately, it's beyond my knowledge and I can't find information about this.  But let me know when you have any progress!

**Comment by Jerther** [comment]
Oh I see. Thanks for the hint. 

From what I gather, apparently there's no way to turn this module (or any other cheap modules like this) into a HID Host. It has something to do with the firmware of these devices. And even it was possible, we would have to write our own drivers.

I think you already have the next best thing with the USB dongles.

There may be a possibility with an ESP32 though:

https://github.com/espressif/esp-idf/tree/master/examples/bluetooth/esp_hid_host

But then this requires an ESP32-IDF compatible model, but I think these models don't support USB HID. To do that, an ESP32-S2 is required.

Anyway this is way out of the scope of your project, and it's gotten way too incertain for me to even consider (time is precious!) so I think I'll forget the idea and either use a true USB keyboard or use your project as is :)

Regards
